import type { CanAffordBreakdown } from "./can-i-afford";
import { getCategoryDefinition } from "./categories";
import type { DashboardAiFactInputs } from "./dashboard";
import type {
  AiDataUseDisclosure,
  AiFact,
  AiInsightSet,
  AiProviderRetentionDisclosure,
  ResolvedPeriod,
} from "./types";

export const AI_DISCLOSURE_VERSION = "2025-02-01";
export const AI_INFORMATIONAL_DISCLAIMER =
  "AI-generated interpretations and recommendations are informational only and are not professional financial advice.";

export const AI_PROVIDER_RETENTION: AiProviderRetentionDisclosure = {
  status: "unverified",
  statement: "Provider retention behavior has not been verified by the product owner.",
};

const INSIGHT_FIELDS = [
  "reporting period dates and label",
  "currency",
  "recorded transaction count",
  "recorded income, spending, and balance totals",
  "recorded spending totals by category",
] as const;

export interface AiProviderPayload {
  period: Pick<ResolvedPeriod, "start" | "end" | "label">;
  currency: string;
  transactionCount: number;
  incomeMinor: number;
  spendingMinor: number;
  balanceMinor: number;
  categorySpending: readonly { categoryId: string; amountMinor: number }[];
}

export interface AiGenerationContext {
  period: ResolvedPeriod;
  facts: readonly AiFact[];
  providerPayload: AiProviderPayload;
}

const SAFE_TO_SPEND_FIELDS = [
  "reporting period dates and label",
  "currency",
  "current balance - income minus expenses so far this period",
  "upcoming recurring bills",
  "reserved goal contributions",
  "expected remaining expenses and remaining period days",
  "computed safe-to-spend amount",
] as const;

export interface SafeToSpendProviderPayload {
  period: Pick<ResolvedPeriod, "start" | "end" | "label">;
  currency: string;
  currentBalanceMinor: number;
  upcomingBillsMinor: number;
  goalContributionMinor: number;
  expectedExpensesMinor: number;
  safeToSpendMinor: number;
  remainingDays: number;
  isDeficit: boolean;
}

const SAFE_TO_SPEND_PURPOSE =
  "Explain the already-calculated safe-to-spend figure in plain language based on the disclosed summary.";
export const AI_INFORMATIONAL_DISCLAIMER_SAFE_TO_SPEND =
  "This explanation was generated by AI and is informational only. It never changes the number shown.";

export function getSafeToSpendDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(SAFE_TO_SPEND_PURPOSE, {
    fields: SAFE_TO_SPEND_FIELDS,
  });
}

export function buildSafeToSpendProviderPayload(
  breakdown: {
    period: ResolvedPeriod;
    currency: string;
    balanceMinor: number;
    upcomingBillsMinor: number;
    goalContributionMinor: number;
    expectedExpensesMinor: number;
    safeToSpendMinor: number;
    remainingDays: number;
    isDeficit: boolean;
  },
): SafeToSpendProviderPayload {
  return {
    period: { start: breakdown.period.start, end: breakdown.period.end, label: breakdown.period.label },
    currency: breakdown.currency,
    currentBalanceMinor: Math.round(breakdown.balanceMinor),
    upcomingBillsMinor: Math.round(breakdown.upcomingBillsMinor),
    goalContributionMinor: Math.round(breakdown.goalContributionMinor),
    expectedExpensesMinor: Math.round(breakdown.expectedExpensesMinor),
    safeToSpendMinor: Math.round(breakdown.safeToSpendMinor),
    remainingDays: breakdown.remainingDays,
    isDeficit: breakdown.isDeficit,
  };
}

const CAN_AFFORD_FIELDS = [
  "reporting period dates and label",
  "currency",
  "purchase price",
  "computed safe-to-spend figure",
  "computed after-purchase balance",
  "months of goal savings the purchase would displace",
  "emergency buffer status",
] as const;

export interface CanAffordProviderPayload {
  period: Pick<ResolvedPeriod, "start" | "end" | "label">;
  currency: string;
  priceMinor: number;
  safeToSpendMinor: number;
  afterPurchaseMinor: number;
  isAffordable: boolean;
  goalImpactMonths: number | null;
  emergencyStatus: "no-goal" | "on-track" | "below-target";
}

const CAN_AFFORD_PURPOSE =
  "Give a plain-language verdict on whether a single planned purchase fits within the app-computed Safe-to-Spend budget.";

export const AI_INFORMATIONAL_DISCLAIMER_CAN_AFFORD =
  "This verdict was generated by AI over the app-computed figures above. It never changes the numbers shown.";

export function getCanAffordDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(CAN_AFFORD_PURPOSE, {
    fields: CAN_AFFORD_FIELDS,
  });
}

export function buildCanAffordProviderPayload(
  breakdown: CanAffordBreakdown,
): CanAffordProviderPayload {
  return {
    period: { start: breakdown.period.start, end: breakdown.period.end, label: breakdown.period.label },
    currency: breakdown.currency,
    priceMinor: Math.round(breakdown.priceMinor),
    safeToSpendMinor: Math.round(breakdown.safeToSpendMinor),
    afterPurchaseMinor: Math.round(breakdown.afterPurchaseMinor),
    isAffordable: breakdown.isAffordable,
    goalImpactMonths: breakdown.goalImpactMonths,
    emergencyStatus: breakdown.emergencyStatus,
  };
}

const GOAL_PLAN_FIELDS = [
  "goal name",
  "saved amount, target amount, and monthly contribution",
  "months remaining until the deadline",
  "required monthly contribution and the monthly gap",
  "candidate category-reduction and recurring-plan amounts",
] as const;

export interface GoalPlanProviderPayload {
  goalName: string;
  currency: string;
  /** Savegoal-id-less numeric summary for narration; no raw descriptions. */
  targetMinor: number;
  currentMinor: number;
  monthlyContributionMinor: number;
  monthsRemaining: number | null;
  requiredMonthlyMinor: number | null;
  contributionGapMinor: number | null;
  /** The smallest subset of levers that covers the gap. */
  selectedLevers: readonly {
    kind: "category-cut" | "subscription-cancel";
    label: string;
    amountMinor: number;
  }[];
  gapRemainingMinor: number;
  isGapCovered: boolean;
}

const GOAL_PLAN_PURPOSE =
  "Explain the app-computed goal-plan math and the levers found to close the monthly gap.";
export const AI_INFORMATIONAL_DISCLAIMER_GOAL_PLAN =
  "This narration was generated by AI over the app-computed plan above. It never changes the numbers shown.";

export function getGoalPlanDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(GOAL_PLAN_PURPOSE, { fields: GOAL_PLAN_FIELDS });
}

export function buildGoalPlanProviderPayload(plan: {
  goalName: string;
  currency: string;
  targetMinor: number;
  currentMinor: number;
  monthlyContributionMinor: number;
  monthsRemaining: number | null;
  requiredMonthlyMinor: number | null;
  contributionGapMinor: number | null;
  selected: readonly { kind: "category-cut" | "subscription-cancel"; label: string; amountMinor: number }[];
  gapRemainingMinor: number;
  isGapCovered: boolean;
}): GoalPlanProviderPayload {
  return {
    goalName: plan.goalName,
    currency: plan.currency,
    targetMinor: Math.round(plan.targetMinor),
    currentMinor: Math.round(plan.currentMinor),
    monthlyContributionMinor: Math.round(plan.monthlyContributionMinor),
    monthsRemaining: plan.monthsRemaining,
    requiredMonthlyMinor: plan.requiredMonthlyMinor !== null ? Math.round(plan.requiredMonthlyMinor) : null,
    contributionGapMinor: plan.contributionGapMinor !== null ? Math.round(plan.contributionGapMinor) : null,
    selectedLevers: plan.selected.map((lever) => ({
      kind: lever.kind,
      label: lever.label,
      amountMinor: Math.round(lever.amountMinor),
    })),
    gapRemainingMinor: Math.round(plan.gapRemainingMinor),
    isGapCovered: plan.isGapCovered,
  };
}

export function createAiDataUseDisclosure(
  purpose: string,
  options: { includeQuestion?: boolean; fields?: readonly string[] } = {},
): AiDataUseDisclosure {
  const fields = options.fields ?? INSIGHT_FIELDS;
  return {
    version: AI_DISCLOSURE_VERSION,
    purpose,
    fields: options.includeQuestion ? [...fields, "submitted question"] : [...fields],
    providerRetention: AI_PROVIDER_RETENTION,
  };
}

const CATEGORY_PURPOSE = "Suggest a transaction category from the description you provide.";
const CATEGORY_FIELDS = ["transaction description"] as const;
const INSIGHTS_PURPOSE = "Generate informational spending interpretations and recommendations from the selected reporting period.";
const ANSWER_PURPOSE = "Answer the submitted question with informational spending analysis from the selected reporting period.";

/**
 * These disclosure getters live outside the `'use server'` action modules so
 * server/client route composition (which only needs the disclosure content,
 * not a server action) can import them without every export of the action
 * module being required to be an async server action.
 */
export function getAiCategoryDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(CATEGORY_PURPOSE, { fields: CATEGORY_FIELDS });
}

export function getAiInsightsDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(INSIGHTS_PURPOSE);
}

export function getAiAnswerDisclosure(): AiDataUseDisclosure {
  return createAiDataUseDisclosure(ANSWER_PURPOSE, { includeQuestion: true });
}

function formatMinorAmount(amountMinor: number, currency: string): string {
  return `${currency} ${(amountMinor / 100).toFixed(2)}`;
}

/**
 * Converts the already-authorized dashboard aggregate into the complete payload
 * permitted by the data-use disclosure. Raw descriptions, IDs, and timestamps
 * are intentionally excluded.
 */
export function buildPeriodScopedAiGenerationContext(
  input: DashboardAiFactInputs,
): AiGenerationContext | null {
  if (input.status === "unavailable") return null;

  const facts: AiFact[] = [
    { label: "Recorded transactions", value: String(input.transactionCount), source: "recorded-data" },
    { label: "Recorded income", value: formatMinorAmount(input.incomeMinor, input.currency), source: "recorded-data" },
    { label: "Recorded spending", value: formatMinorAmount(input.spendingMinor, input.currency), source: "recorded-data" },
    { label: "Recorded balance", value: formatMinorAmount(input.balanceMinor, input.currency), source: "recorded-data" },
    ...input.categorySpending.map(({ categoryId, amountMinor }) => ({
      label: `Recorded spending: ${getCategoryDefinition(categoryId).label}`,
      value: formatMinorAmount(amountMinor, input.currency),
      source: "recorded-data" as const,
    })),
  ];

  return {
    period: input.period,
    facts,
    providerPayload: {
      period: { start: input.period.start, end: input.period.end, label: input.period.label },
      currency: input.currency,
      transactionCount: input.transactionCount,
      incomeMinor: input.incomeMinor,
      spendingMinor: input.spendingMinor,
      balanceMinor: input.balanceMinor,
      categorySpending: input.categorySpending.map(({ categoryId, amountMinor }) => ({
        categoryId,
        amountMinor,
      })),
    },
  };
}

/** Returns a new retained result for a failed refresh without mutating the last success. */
export function markAiInsightSetStale(insightSet: AiInsightSet): AiInsightSet {
  return { ...insightSet, stale: true };
}
